apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: csamp-tanzu-java-web-app
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/cgsamp/tanzu-java-web-app
      ref:
        branch: main