apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterImageTemplate/kpack-template;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterImageTemplate","metadata":{"labels":{"kapp.k14s.io/app":"1683666878925880811","kapp.k14s.io/association":"v1.4543b39a9204f82bc4eba330b4fc99ba"},"name":"kpack-template"},"spec":{"healthRule":{"multiMatch":{"healthy":{"matchConditions":[{"status":"True","type":"BuilderReady"},{"status":"True","type":"Ready"}]},"unhealthy":{"matchConditions":[{"status":"False","type":"BuilderReady"},{"status":"False","type":"Ready"}]}}},"imagePath":".status.latestImage","params":[{"default":"default","name":"serviceAccount"},{"default":"default","name":"clusterBuilder"},{"default":{},"name":"registry"},{"default":[],"name":"buildServiceBindings"}],"ytt":"#@
      load(\"@ytt:data\", \"data\")\n\n#@ def merge_labels(fixed_values):\n#@   labels
      = {}\n#@   if hasattr(data.values.workload.metadata, \"labels\"):\n#@     labels.update(data.values.workload.metadata.labels)\n#@   end\n#@   labels.update(fixed_values)\n#@   return
      labels\n#@ end\n\n#@ def param(key):\n#@   if not key in data.values.params:\n#@     return
      None\n#@   end\n#@   return data.values.params[key]\n#@ end\n\n#@ def image():\n#@   return
      \"/\".join([\n#@    data.values.params.registry.server,\n#@    data.values.params.registry.repository,\n#@    \"-\".join([\n#@      data.values.workload.metadata.name,\n#@      data.values.workload.metadata.namespace,\n#@    ])\n#@   ])\n#@
      end\n\napiVersion: kpack.io/v1alpha2\nkind: Image\nmetadata:\n  name: #@ data.values.workload.metadata.name\n  labels:
      #@ merge_labels({ \"app.kubernetes.io/component\": \"build\" })\nspec:\n  tag:
      #@ image()\n  serviceAccountName: #@ data.values.params.serviceAccount\n  builder:\n    kind:
      ClusterBuilder\n    name: #@ data.values.params.clusterBuilder\n  source:\n    blob:\n      url:
      #@ data.values.source.url\n    #@ if hasattr(data.values.workload.spec, \"source\"):\n    #@
      if/end hasattr(data.values.workload.spec.source, \"subPath\"):\n    subPath:
      #@ data.values.workload.spec.source.subPath\n    #@ end\n  build:\n    env:\n    -
      name: BP_OCI_SOURCE\n      value: #@ data.values.source.revision\n    #@ if/end
      param(\"live-update\"):\n    - name: BP_LIVE_RELOAD_ENABLED\n      value: ''true''\n    #@
      if hasattr(data.values.workload.spec.build, \"env\"):\n    #@ for var in data.values.workload.spec.build.env:\n    -
      name: #@ var.name\n      #@ if/end hasattr(var, \"value\"):\n      value: #@
      var.value\n      #@ if/end hasattr(var, \"valueFrom\"):\n      valueFrom: #@
      var.valueFrom\n    #@ end\n    #@ end\n    services: #@ data.values.params.buildServiceBindings\n"}}'
    kapp.k14s.io/original-diff-md5: 8e1ca9893e5a176f4f857f553ca2442f
  creationTimestamp: "2023-05-09T21:14:41Z"
  generation: 1
  labels:
    kapp.k14s.io/app: "1683666878925880811"
    kapp.k14s.io/association: v1.4543b39a9204f82bc4eba330b4fc99ba
  name: kpack-template
  resourceVersion: "129560"
  uid: 48f0cf8c-faee-4a53-9c1b-e98837c07756
spec:
  healthRule:
    multiMatch:
      healthy:
        matchConditions:
        - status: "True"
          type: BuilderReady
        - status: "True"
          type: Ready
      unhealthy:
        matchConditions:
        - status: "False"
          type: BuilderReady
        - status: "False"
          type: Ready
  imagePath: .status.latestImage
  lifecycle: mutable
  params:
  - default: default
    name: serviceAccount
  - default: default
    name: clusterBuilder
  - default: {}
    name: registry
  - default: []
    name: buildServiceBindings
  ytt: |
    #@ load("@ytt:data", "data")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry.server,
    #@    data.values.params.registry.repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@    ])
    #@   ])
    #@ end

    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: #@ data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "build" })
    spec:
      tag: #@ image()
      serviceAccountName: #@ data.values.params.serviceAccount
      builder:
        kind: ClusterBuilder
        name: #@ data.values.params.clusterBuilder
      source:
        blob:
          url: #@ data.values.source.url
        #@ if hasattr(data.values.workload.spec, "source"):
        #@ if/end hasattr(data.values.workload.spec.source, "subPath"):
        subPath: #@ data.values.workload.spec.source.subPath
        #@ end
      build:
        env:
        - name: BP_OCI_SOURCE
          value: #@ data.values.source.revision
        #@ if/end param("live-update"):
        - name: BP_LIVE_RELOAD_ENABLED
          value: 'true'
        #@ if hasattr(data.values.workload.spec.build, "env"):
        #@ for var in data.values.workload.spec.build.env:
        - name: #@ var.name
          #@ if/end hasattr(var, "value"):
          value: #@ var.value
          #@ if/end hasattr(var, "valueFrom"):
          valueFrom: #@ var.valueFrom
        #@ end
        #@ end
        services: #@ data.values.params.buildServiceBindings
